# Use Azure Open AI with key
provider: autogen_ext.models.openai.AzureOpenAIChatCompletionClient
config:
   model: gpt-4.1-mini
   azure_endpoint: "https://aq-aoai-swedencentral.openai.azure.com/"
   azure_deployment: gpt-4.1-mini
   api_version: "2025-03-01-preview"
   api_key: "8wu7cijnUsEVZw5VMZIIArMFHU6TvoVuyOCthC0wCQW5e5xRSlxnJQQJ99BFACfhMk5XJ3w3AAABACOGteSd"